### PR TITLE
Extend "Background" to include an environment map

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Basic 2D images (jpg, png, etc.) can now be loaded as environment maps. This affects the illumination of objects in the scene for PBR materials.

Furthermore, we've added GUI controls for the default gradient colors so it can be set in session rather than strictly through the API. The addition of GUI controls means that the preferred path to Background is no longer simply `/Background`, but `/Background/<object>`. That said, the old spelling still works but prompts users to change their reference.

Finally, we've modified the meshfile_object.gltf.html test/example to include the environment map (it already has an object which can easily be made metallic to show reflection of the environment map). The page also gets an encoded environment map -- a custom image representing the classic Cornell box.

The basic logic is that if an environment map is defined, it is used for both background and material environment. However, there is an option for those who feel the rendered environment map is too distracting; it can be decoupled from the environment map and simply render the gradient -- the gradient will not illuminate materials in this case.

- - -
This change is [Reviewable](https://reviewable.io/reviews/rdeits/meshcat/148)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
image

You can see the effect of the environment map in this image that shows a metallic cube reflecting both the light and the Cornell-box environment.

**Comment by SeanCurtis-TRI** [comment]
You should also be able to confirm that the gradients in the other test html files still work (and are now editable in browser).

**Review by RussTedrake — CHANGES_REQUESTED** [review]
Looks very cool.  A few comments/requests below.  Otherwise :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rdeits/meshcat/148#-:-NaHGqrX5kglxCkBDo52:b4278bt)* status: all files reviewed, 5 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[`src/index.js` line 325 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHGzaYAvAmji0meCTu:-NaHGzaYAvAmji0meCTv:bbeg3g5) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L325)):*
> ```JavaScript
>     // background is visible or not.
>     update(scene, is_visible) {
>         // TODO: If the background simply isn't visible, defer the work until
> ```

Add your name to the TODO?  (I know that's a Drake thing, but it seems still good form here)
___
*[`src/index.js` line 472 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHGj274lSOVlo4nIXk:-NaHGj274lSOVlo4nIXl:bg75xrb) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L472)):*
> ```JavaScript
>             // Changing the background gradient is cheap, so we'll change the
>             // color in the onChange() callback (instead of the onChangeFinished)
>             // callback -- it makes a more interactive experience.
> ```

btw -- yes... pretty slick
___
*[`src/index.js` line 520 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHGarC8hBJCt9vAqJ0:-NaHGarC8hBJCt9vAqJ1:bmihkib) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L520)):*
> ```JavaScript
>         }
>         if (this.object.isBackground) {
>             // If we've set values on the Background, we need to fire it on_update()).
> ```

nit: grammar "fire it on_update"
___
*[`src/index.js` line 803 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHG9wY14qlLXVATKZZ:-NaHG9wY14qlLXVATKZ_:b1zly6) ([raw file](https://github.com/rdeits/meshcat/blob/120cbc1f57b10a15efac2b79f38f19b8bdd44722/src/index.js#L803)):*
> ```JavaScript
>     }
> 
>     hide_background() {
> ```

this is a breaking change... there could be code calling this directly.  
it should be possible to provide thin implementations that call update_background and maintain the functionality?
___
*[`src/index.js` line 1018 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHFvtK1xRtYp7-fRpv:-NaHFvtK1xRtYp7-fRpw:bhtsdxo) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L1018)):*
> ```JavaScript
>     }
> 
>     strip_visibility_control(node) {
> ```

is this unused?  or am I not finding the call site? can we zap it?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Excellent comments. Cleaned up now, I believe.

> *[Reviewable](https://reviewable.io/reviews/rdeits/meshcat/148#-:-NaJaBWi8mEBTplyfAjd:b-xqge59)* status: all files reviewed, 3 unresolved discussions (waiting on @RussTedrake)

___
*[`src/index.js` line 325 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHGzaYAvAmji0meCTu:-NaJFaC16Ba0ivTYxPLk:b1j279i) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L325)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Add your name to the TODO?  (I know that's a Drake thing, but it seems still good form here)
</blockquote></details>

Done

meshcat's previous TODOs didn't have names. But then I didn't consistently follow that pattern, so my name does appear sporadically. I'm certainly willing to take ownership.  :)
___
*[`src/index.js` line 803 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHG9wY14qlLXVATKZZ:-NaJFzC_AW0fvL22FbEx:bb6un1j) ([raw file](https://github.com/rdeits/meshcat/blob/120cbc1f57b10a15efac2b79f38f19b8bdd44722/src/index.js#L803)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this is a breaking change... there could be code calling this directly.  
it should be possible to provide thin implementations that call update_background and maintain the functionality?
</blockquote></details>

Done
___
*[`src/index.js` line 1018 at r1](https://reviewable.io/reviews/rdeits/meshcat/148#-NaHFvtK1xRtYp7-fRpv:-NaJGvh183YSA2_ePlLt:b-5pdd4c) ([raw file](https://github.com/rdeits/meshcat/blob/51dd44dea228fa24a5edc046202451d29074b89f/src/index.js#L1018)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

is this unused?  or am I not finding the call site? can we zap it?
</blockquote></details>

Relic of previous approach.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rdeits/meshcat/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Pull request merged**
