### PR TITLE
Add billboard capability

### PR DESCRIPTION
**Pull request by kingjin94**
Add sprite drawing as a way to add billboards (2D text annotations that always face the camera). Allows to write text unto the scene.

An example:

Screenshot from 2023-07-03 14-26-30

Send json:

```
{
    u"metadata": {
        u"version": 4.5,
        u"type": u"_billboard",
    },
    u"geometries": [],
    u"materials": [],
    u"object": {
        u"uuid": <some_uuid>,
        u"type": u"_billboard",
        u"text": "test444"
        u"base_width": 75,
        u"size": 16,
        u"global_scale": 0.01,
        u"matrix": np.eye(4).flatten().tolist(),
        u"text_color": "white",
        u"background_color": "blue",
    }
}
```

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think we can already do this, without any new javascript.  Here's a sample message:

```
        viewer.handle_command({
            type: "set_object",
            path: "/meshcat/sprite",
            object: {
                metadata: {
                    version: 4.5,
                    type: "Object"
                },
                textures: [
                    {
                        uuid: "0c8c99a8-bba8-11ee-b7a2-4b79088b524d",
                        type: "_text",
                        text: "Hello, world!",
                        font_size: 300,
                        font_face: "sans-serif"
                    }
                ],
                materials: [
                    {
                        uuid: "6fe7011b-bba7-11ee-b7a2-4b79088b524d",
                        type: "SpriteMaterial",
                        transparent: true,
                        map: "0c8c99a8-bba8-11ee-b7a2-4b79088b524d"
                    }
                ],
                object: {
                    uuid: "6fe7011c-bba7-11ee-b7a2-4b79088b524d",
                    type: "Sprite",
                    // geometry: "6fe70119-bba7-11ee-b7a2-4b79088b524d",
                    material: "6fe7011b-bba7-11ee-b7a2-4b79088b524d"
                }
            }
        });
```

**Comment by jwnimmer-tri** [comment]
In https://github.com/meshcat-dev/meshcat/pull/173, I have a demo that shows this feature might already be available.  If you have a change, please let us know if there's still something missing.

**Comment by jwnimmer-tri** [comment]
For now, I'll assume that https://github.com/meshcat-dev/meshcat/pull/173 was sufficient.  If not, please let us know -- e.g., open a new pull request with more details.

**Comment by soulslicer** [comment]
@jwnimmer-tri Your example works, but can you please tell me how to change the text color or add a background around it

**Comment by jwnimmer-tri** [comment]
I don't have any information about that.  Take the demo and play around with it, and/or consult the three.js documentation about sprites and materials.

**Pull request closed without merging**
